print("INTEGERS ONLY")
num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result = int(num1) + int(num2)
print(result)

print("with commas")
num3 = input("Enter a number: ")
num4 = input("Enter another number: ")
result = float(num3) + float(num4)
print(result)