print("Ralph Tashinga")
print("Rutendo\nFortunate")
print("Rutendo\"Fortunate\"")
print("Ralph\\Tashinga")
phrase = "Ralph Nyoni "
print(phrase + "is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[3])
print(phrase.index("Nyoni"))
print(phrase.replace("Nyoni", "Tashinga"))